apiVersion: v1
kind: Service
metadata:
  name: smart-cost-optimizer-api
spec:
  selector:
    app: smart-cost-optimizer-api
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
