apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-cost-optimizer-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: smart-cost-optimizer-frontend
  template:
    metadata:
      labels:
        app: smart-cost-optimizer-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
