apiVersion: v1
kind: Service
metadata:
  name: smart-cost-optimizer-frontend
spec:
  selector:
    app: smart-cost-optimizer-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
